ANpassung 50Hert geojson Insel baumwerder weil intecept
GEOSException: TopologyException: side location conflict at 11.475045430883664 53.963776528580894 0